name: Python API Linting and Testing

on:
  push:
    branches: ["main"]
    paths: 'api-python/*'

permissions:
  checks: write
  contents: write

jobs:
  run-linters:
    name: Run linters
    runs-on: ubuntu-latest
    
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      # Install your linters here

      - name: Run linters
        uses: wearerequired/lint-action@v2
        with:
            pylint: true

      - name: Run ruff
        uses: davidslusser/actions_python_ruff@v1.0.1